### ISSUE TITLE
Dividir as pastas dos repositórios dos jogos em novos repositóriso dentro do grupo LARVA

### ISSUE THREAD

**Issue by huenato** [UDESC-LARVA/LARVA#1]
fica mais facil de criar sites pelo github io

**Comment by gabrielcaixeta** [comment]
@huenato concordo totalmente.
@Olorin-Narya poderias criar os repositórios dos jogos para nós?

**Comment by Olorin-Narya** [comment]
@huenato @gabrielcaixeta feito, vcs nao tao no LARVA, convidei vcs.
